"""
MVP destination content (PROJECT_SPEC.md §10). The spec's bulleted list names 29
destinations, not 30, despite the section header claiming 30 (an inconsistency in
the source spec - flagged in README.md rather than padded with an invented 30th).

Every entry here covers all 8 `category` values and all 8 `mechanism_type` values
(the spec's own "9 mechanism types" phrasing is likewise off by one - see the
`registration_window` note in app/schemas/mechanism_config.py; there are 8 declared
enum values and PCT/JMT deliberately reuse `lottery` rather than adding a 9th).

Source URLs point at the real official/primary booking sources for these permits
based on general knowledge; `last_verified_at` is intentionally left null so an
admin confirms each one via the admin panel before fully trusting it (per §8, this
app never auto-publishes changes to destination content).

checklist: item_type in {document, action, gear, payment}, is_required bool.
"""

DESTINATIONS = [
    dict(
        country="Peru", category="trek", name="Inca Trail",
        mechanism_type="fixed_daily_quota",
        mechanism_config={"daily_quota": 500, "booking_opens_days_before": 180},
        issuing_authority="government", competitiveness_level="very_high",
        source_url="https://www.machupicchu.gob.pe/",
        name_he="שביל האינקה",
        description_en="The classic 4-day trek to Machu Picchu through the Peruvian Andes, ending at the Sun Gate.",
        mechanism_explanation_en="A hard daily cap of 500 permits (hikers plus guides and porters) is sold through licensed tour operators, typically 5-6 months ahead of peak season.",
        checklist=[
            ("document", "Valid passport (must match the name on your permit exactly)", True),
            ("action", "Book through a licensed tour operator - independent trekking is not permitted", True),
            ("document", "Booking confirmation / permit number from your operator", True),
            ("gear", "Sleeping bag rated for cold nights (camps sit above 3,000m)", False),
            ("payment", "Full trek payment, usually required in advance to secure the permit", True),
        ],
    ),
    dict(
        country="Rwanda", category="wildlife_safari", name="Mountain Gorilla Trekking – Volcanoes NP",
        mechanism_type="fixed_daily_quota",
        mechanism_config={"daily_quota": 96, "booking_opens_days_before": 365},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.rdb.rw/tourism/",
        name_he="מסע לצפייה בגורילות הרים",
        description_en="A guided trek to visit one of the habituated gorilla families in Volcanoes National Park.",
        mechanism_explanation_en="Only 8 visitors per gorilla family per day are permitted, across roughly 12 habituated families. Permits can be booked up to a year in advance and sell out early in peak season (June-Sept, Dec-Feb).",
        checklist=[
            ("document", "Gorilla permit (issued by Rwanda Development Board)", True),
            ("document", "Passport valid for 6+ months", True),
            ("gear", "Sturdy waterproof hiking boots", True),
            ("gear", "Gardening-style gloves for grabbing vegetation on the trail", False),
            ("action", "Arrive at park HQ for a 07:00 briefing on trek day", True),
        ],
    ),
    dict(
        country="Malaysia", category="diving", name="Sipadan",
        mechanism_type="fixed_daily_quota",
        mechanism_config={"daily_quota": 176, "booking_opens_days_before": 90},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.sabahparks.org.my/",
        name_he="סיפדן",
        description_en="One of the world's top dive sites, famous for barracuda tornadoes and green turtles - access is capped to protect the reef.",
        mechanism_explanation_en="Sabah Parks caps Sipadan at exactly 176 diver permits per day, allocated to dive operators based in nearby Mabul/Semporna. Permits are typically arranged by your dive resort 2-3 months ahead.",
        checklist=[
            ("document", "Sipadan dive permit (arranged by your resort/operator)", True),
            ("document", "Proof of Open Water certification (or higher)", True),
            ("gear", "Your own dive computer (recommended, not always provided)", False),
            ("payment", "Marine park conservation fee", True),
        ],
    ),
    dict(
        country="Costa Rica", category="national_park_entry", name="Corcovado NP – Sirena Station",
        mechanism_type="fixed_daily_quota",
        mechanism_config={"daily_quota": 80, "booking_opens_days_before": 30},
        issuing_authority="government", competitiveness_level="medium",
        source_url="https://www.sinac.go.cr/",
        name_he="פארק קורקובדו - תחנת סירנה",
        description_en="The most remote and wildlife-rich ranger station in Corcovado National Park, reachable only by boat, plane, or a full-day hike.",
        mechanism_explanation_en="SINAC caps daily visitor numbers at Sirena Station and requires a certified local guide for entry; book through SINAC or an authorized operator about a month ahead in high season.",
        checklist=[
            ("action", "Book through SINAC or a licensed operator with a certified guide", True),
            ("document", "Park entrance permit / reservation confirmation", True),
            ("gear", "Rubber boots or quick-dry shoes for river crossings", False),
            ("payment", "Park entrance fee", True),
        ],
    ),
    dict(
        country="USA", category="trek", name="Half Dome",
        mechanism_type="lottery",
        mechanism_config={"application_window_start": "03-01", "application_window_end": "03-31", "results_date": "04-15"},
        issuing_authority="government", competitiveness_level="very_high",
        source_url="https://www.nps.gov/yose/planyourvisit/hdpermits.htm",
        name_he="הכיפה החצויה",
        description_en="The iconic cable-assisted final ascent to the summit of Half Dome in Yosemite National Park.",
        mechanism_explanation_en="A preseason lottery runs each March for the whole hiking season; a smaller daily lottery also opens 2 days before each hiking date for leftover permits.",
        checklist=[
            ("action", "Enter the preseason lottery on recreation.gov in March", True),
            ("document", "Half Dome permit (one per hiker, must be carried)", True),
            ("gear", "Gloves for the cable section", False),
            ("document", "Yosemite park entrance pass", True),
        ],
    ),
    dict(
        country="USA", category="trek", name="Mount Whitney",
        mechanism_type="lottery",
        mechanism_config={"application_window_start": "02-01", "application_window_end": "03-15", "results_date": "04-15"},
        issuing_authority="government", competitiveness_level="very_high",
        source_url="https://www.recreation.gov/permits/233260",
        name_he="הר וויטני",
        description_en="The tallest peak in the contiguous United States, climbed via the popular Whitney Main Trail.",
        mechanism_explanation_en="The Inyo National Forest runs an annual lottery each February-March for day-use and overnight quota permits during the peak May-October season.",
        checklist=[
            ("action", "Enter the Whitney Zone lottery on recreation.gov", True),
            ("document", "Wilderness permit (day-use or overnight)", True),
            ("gear", "WAG bag (human waste pack-out kit, required above Trail Camp)", True),
            ("gear", "Bear canister for overnight trips", True),
        ],
    ),
    dict(
        country="USA", category="trek", name="Angels Landing",
        mechanism_type="lottery",
        mechanism_config={"application_window_start": "01-01", "application_window_end": "01-20", "results_date": "01-24"},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.nps.gov/zion/planyourvisit/angels-landing-permits.htm",
        name_he="אנג'לס לנדינג",
        description_en="A steep, chain-assisted final ascent above Zion Canyon with sheer drop-offs on both sides.",
        mechanism_explanation_en="Zion NP runs seasonal lotteries (one per season) plus a day-before lottery. This entry models the season-opening lottery window; check the source for the current season's exact dates.",
        checklist=[
            ("action", "Enter the seasonal lottery on recreation.gov", True),
            ("document", "Angels Landing permit (checked at the chains)", True),
            ("gear", "Gloves for the chain sections", False),
        ],
    ),
    dict(
        country="USA", category="national_park_entry", name="Grand Canyon Colorado River Rafting",
        mechanism_type="lottery",
        mechanism_config={"application_window_start": "02-01", "application_window_end": "02-20", "results_date": "06-01"},
        issuing_authority="government", competitiveness_level="very_high",
        source_url="https://www.nps.gov/grca/planyourvisit/rivertrip.htm",
        name_he="ריאפטינג בנהר קולורדו - הגרנד קניון",
        description_en="A self-guided (noncommercial) multi-day whitewater rafting trip through the Grand Canyon.",
        mechanism_explanation_en="A weighted lottery is held each February for noncommercial river trip launch dates the following year - your odds improve each year you're not selected.",
        checklist=[
            ("action", "Enter the weighted noncommercial lottery in February", True),
            ("document", "River trip permit with assigned launch date", True),
            ("gear", "Self-bailing raft or dory and full safety kit", True),
            ("action", "Attend the mandatory pre-trip orientation", True),
        ],
    ),
    dict(
        country="USA", category="trek", name="The Wave / Coyote Buttes North",
        mechanism_type="lottery",
        mechanism_config={"application_window_start": "01-01", "application_window_end": "01-31", "results_date": "02-15"},
        issuing_authority="government", competitiveness_level="very_high",
        source_url="https://www.blm.gov/visit/coyote-buttes",
        name_he="הגל / קויוטי בוטס צפון",
        description_en="A surreal sandstone rock formation on the Arizona-Utah border, limited to a handful of hikers per day.",
        mechanism_explanation_en="BLM runs both an advance monthly online lottery and a daily walk-in lottery; only a small number of permits are issued per day, so competition is fierce.",
        checklist=[
            ("action", "Enter the monthly advance lottery on recreation.gov", True),
            ("document", "Coyote Buttes North permit (printed or digital)", True),
            ("gear", "GPS or offline map - there is no marked trail", True),
            ("gear", "4+ liters of water per person, no shade on route", True),
        ],
    ),
    dict(
        country="USA", category="thru_hike", name="Wonderland Trail",
        mechanism_type="lottery",
        mechanism_config={"application_window_start": "02-15", "application_window_end": "03-15", "results_date": "04-01"},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.nps.gov/mora/planyourvisit/wonderland-trail-permit.htm",
        name_he="שביל וונדרלנד",
        description_en="A 93-mile loop encircling Mount Rainier, typically hiked over 10-14 days.",
        mechanism_explanation_en="Mount Rainier NP holds an early-access lottery each spring for a limited number of complete-itinerary wilderness permits; remaining permits release on a rolling first-come basis afterward.",
        checklist=[
            ("action", "Enter the early-access lottery in Feb-Mar", True),
            ("document", "Wilderness permit with assigned campsite itinerary", True),
            ("gear", "Bear canister (required trail-wide)", True),
            ("gear", "Water treatment (filter or tablets)", True),
        ],
    ),
    dict(
        country="USA", category="camping", name="Yellowstone Backcountry Permit",
        mechanism_type="lottery",
        mechanism_config={"application_window_start": "03-01", "application_window_end": "03-20", "results_date": "04-01"},
        issuing_authority="government", competitiveness_level="medium",
        source_url="https://www.nps.gov/yell/planyourvisit/backcountry-permits.htm",
        name_he="קמפינג בשטח הפרא של ילוסטון",
        description_en="Backcountry campsite permits for multi-day trips across Yellowstone's trail network.",
        mechanism_explanation_en="An early-access lottery in March allocates a portion of backcountry campsites for the upcoming season; the rest open on a rolling basis afterward.",
        checklist=[
            ("action", "Enter the early-access lottery in March (optional but recommended for popular sites)", False),
            ("document", "Backcountry camping permit with assigned sites", True),
            ("gear", "Bear-resistant food storage (bear pole/canister per site rules)", True),
        ],
    ),
    dict(
        country="Peru", category="tourist_attraction", name="Machu Picchu entrance tickets",
        mechanism_type="rolling_window",
        mechanism_config={"days_before_travel_date": 90},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.machupicchu.gob.pe/",
        name_he="כרטיסי כניסה למאצ'ו פיצ'ו",
        description_en="Timed-entry tickets to the Machu Picchu citadel, with optional add-on hikes (Huayna Picchu, Machu Picchu Mountain).",
        mechanism_explanation_en="Tickets go on sale roughly 90 days ahead of any given date; popular circuits and the mountain add-ons sell out first, especially in dry season (May-Sept).",
        checklist=[
            ("document", "Timed-entry ticket for your chosen circuit", True),
            ("document", "Passport matching the ticket exactly", True),
            ("payment", "Add-on ticket if climbing Huayna Picchu or Machu Picchu Mountain", False),
        ],
    ),
    dict(
        country="USA", category="tourist_attraction", name="Statue of Liberty Crown Access",
        mechanism_type="rolling_window",
        mechanism_config={"days_before_travel_date": 180},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.nps.gov/stli/planyourvisit/crown-access.htm",
        name_he="גישה לכתר פסל החירות",
        description_en="Access to the crown of the Statue of Liberty, a narrow spiral stair with strictly limited daily capacity.",
        mechanism_explanation_en="Crown tickets are released roughly 6 months ahead and are a small subset of general Liberty Island tickets, so they sell out well before regular tickets.",
        checklist=[
            ("document", "Crown-access ticket (separate from general Liberty Island ticket)", True),
            ("document", "Government-issued photo ID matching the ticket", True),
            ("action", "Arrive well before your timed entry for mandatory security screening", True),
        ],
    ),
    dict(
        country="France", category="tourist_attraction", name="Eiffel Tower Summit Access",
        mechanism_type="rolling_window",
        mechanism_config={"days_before_travel_date": 60},
        issuing_authority="commercial", competitiveness_level="medium",
        source_url="https://www.toureiffel.paris/en",
        name_he="גישה לפסגת מגדל אייפל",
        description_en="Elevator access all the way to the top (3rd) level of the Eiffel Tower, above the more commonly booked 2nd-floor tickets.",
        mechanism_explanation_en="Summit tickets open for sale roughly 60 days ahead and are more limited than 2nd-floor-only tickets, selling out first for peak-season evening slots.",
        checklist=[
            ("document", "Timed summit-access ticket", True),
            ("action", "Arrive 15-30 minutes before your slot for security screening", True),
        ],
    ),
    dict(
        country="USA", category="camping", name="Havasupai Falls",
        mechanism_type="fixed_annual_date",
        mechanism_config={"typical_release_date": "02-01", "release_time": "08:00", "timezone": "America/Phoenix"},
        issuing_authority="tribal", competitiveness_level="very_high",
        source_url="https://www.havasupaireservations.com/",
        name_he="מפלי האוואסופאי",
        description_en="Turquoise waterfalls on Havasupai Tribe land deep in a side canyon of the Grand Canyon, reached by a 10-mile hike or mule/helicopter.",
        mechanism_explanation_en="The Havasupai Tribe releases the entire year's campground reservations in one go on February 1st; the full season typically sells out within hours.",
        checklist=[
            ("document", "Campground reservation confirmation (non-transferable, ID checked at trailhead)", True),
            ("document", "Photo ID matching the reservation name", True),
            ("payment", "Full reservation deposit paid at time of booking", True),
            ("gear", "Water filter or purification (village store water isn't guaranteed)", False),
        ],
    ),
    dict(
        country="Canada", category="trek", name="West Coast Trail",
        mechanism_type="fixed_annual_date",
        mechanism_config={"typical_release_date": "01-10", "release_time": "08:00", "timezone": "America/Vancouver"},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://reservation.pc.gc.ca/",
        name_he="שביל החוף המערבי",
        description_en="A rugged 75km coastal backpacking trail through Pacific Rim National Park Reserve, with ladders, cable cars, and tidal crossings.",
        mechanism_explanation_en="Parks Canada opens the reservation system for the entire upcoming season (May-Sept) on a fixed January date; peak-season start dates fill within the first day.",
        checklist=[
            ("document", "Overnight use permit / reservation confirmation", True),
            ("action", "Attend the mandatory orientation session at a trailhead before starting", True),
            ("gear", "Tide table for the trail season", True),
            ("payment", "Trail use fee and ferry crossing fees", True),
        ],
    ),
    dict(
        country="New Zealand", category="trek", name="Milford Track",
        mechanism_type="fixed_annual_date",
        mechanism_config={"typical_release_date": "05-20", "release_time": "09:00", "timezone": "Pacific/Auckland"},
        issuing_authority="government", competitiveness_level="very_high",
        source_url="https://www.doc.govt.nz/parks-and-recreation/tracks-and-walks/milford-track/",
        name_he="שביל מילפורד",
        description_en="New Zealand's best-known Great Walk, a 4-day guided or independent tramp through Fiordland National Park.",
        mechanism_explanation_en="The Department of Conservation opens bookings for the whole upcoming Great Walks season (Oct-Apr) on one fixed date each May; independent (non-guided) huts sell out within days.",
        checklist=[
            ("document", "Great Walks hut/campsite booking confirmation for all nights", True),
            ("action", "Book a Milford Sound water taxi/track transport in advance", True),
            ("gear", "Full wet-weather gear (rain is near-constant in Fiordland)", True),
        ],
    ),
    dict(
        country="New Zealand", category="trek", name="Routeburn Track",
        mechanism_type="fixed_annual_date",
        mechanism_config={"typical_release_date": "05-20", "release_time": "09:00", "timezone": "Pacific/Auckland"},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.doc.govt.nz/parks-and-recreation/tracks-and-walks/routeburn-track/",
        name_he="שביל ראוטבורן",
        description_en="A 2-3 day alpine Great Walk crossing between Fiordland and Mount Aspiring National Parks.",
        mechanism_explanation_en="Bookings for the whole Great Walks season open on the same fixed May date as the other Great Walks; huts on this shorter, more accessible track fill quickly.",
        checklist=[
            ("document", "Great Walks hut/campsite booking confirmation", True),
            ("action", "Arrange transport between the two trailheads (it's a one-way track)", True),
            ("gear", "Layered clothing for rapid alpine weather changes", True),
        ],
    ),
    dict(
        country="Netherlands", category="tourist_attraction", name="Anne Frank House",
        mechanism_type="weekly_release",
        mechanism_config={"release_weekday": "tuesday", "release_time": "10:00", "timezone": "Europe/Amsterdam", "weeks_ahead": 6},
        issuing_authority="mixed", competitiveness_level="high",
        source_url="https://www.annefrank.org/en/museum/tickets/",
        name_he="בית אנה פרנק",
        description_en="The preserved hiding place of Anne Frank's family during WWII, now a museum in central Amsterdam.",
        mechanism_explanation_en="New tickets release every Tuesday at 10:00 CET for dates roughly 6 weeks out, and typically sell out within minutes.",
        checklist=[
            ("document", "Timed-entry e-ticket", True),
            ("action", "Arrive within your 15-minute entry window - late arrivals may be refused", True),
        ],
    ),
    dict(
        country="USA", category="thru_hike", name="PCT Long-distance Permit",
        mechanism_type="lottery",
        mechanism_config={
            "application_window_start": "01-24", "application_window_end": "01-31", "results_date": "02-05",
            "registration_window": {"start": "01-10", "end": "01-23"},
        },
        issuing_authority="mixed", competitiveness_level="high",
        source_url="https://www.pcta.org/discover-the-trail/permits/",
        name_he="היתר מסלול ארוך - PCT",
        description_en="The single long-distance permit covering travel through most of the 2,650-mile Pacific Crest Trail for thru- and section-hikers.",
        mechanism_explanation_en="A two-stage process: register during the registration_window to become eligible, then permits are awarded via a lottery held shortly after, drawn in timed batches.",
        checklist=[
            ("action", "Register during the registration window on the PCTA site", True),
            ("action", "Enter the long-distance permit lottery", True),
            ("document", "PCT long-distance permit (covers most land-manager jurisdictions)", True),
            ("document", "California campfire permit (separate, free)", True),
        ],
    ),
    dict(
        country="USA", category="thru_hike", name="John Muir Trail",
        mechanism_type="lottery",
        mechanism_config={
            "application_window_start": "01-24", "application_window_end": "03-15", "results_date": "03-24",
            "registration_window": {"start": "01-01", "end": "01-23"},
        },
        issuing_authority="government", competitiveness_level="very_high",
        source_url="https://www.nps.gov/yose/planyourvisit/wilderness-permits.htm",
        name_he="שביל ג'ון מיור",
        description_en="A 211-mile trail through the Sierra Nevada from Yosemite Valley to Mount Whitney's summit.",
        mechanism_explanation_en="Most JMT hikers apply through Yosemite's wilderness permit lottery for a Donohue Pass exit quota; a short registration period precedes the lottery draw itself.",
        checklist=[
            ("action", "Register, then enter Yosemite's wilderness permit lottery", True),
            ("document", "Wilderness permit with Donohue Pass exit quota", True),
            ("gear", "Bear canister (required across most of the route)", True),
        ],
    ),
    dict(
        country="Chile", category="trek", name="Torres del Paine W Circuit",
        mechanism_type="first_come_first_served",
        mechanism_config={"typical_booking_lead_time_months": 6},
        issuing_authority="mixed", competitiveness_level="high",
        source_url="https://www.parquetorresdelpaine.cl/en/reservations/",
        name_he="מעגל ה-W בטורס דל פיינה",
        description_en="The classic 4-5 day W-shaped route through Torres del Paine National Park, staying in a mix of refugios and campsites.",
        mechanism_explanation_en="Every night's accommodation (refugio or campsite) must be individually reserved with its specific concessionaire; popular refugios in peak season (Dec-Feb) fill up around 6 months ahead.",
        checklist=[
            ("document", "Refugio/campsite reservation confirmation for every night of the route", True),
            ("document", "Park entrance ticket", True),
            ("payment", "Deposit or full payment for each refugio, per its own policy", True),
        ],
    ),
    dict(
        country="South Africa", category="trek", name="Otter Trail",
        mechanism_type="first_come_first_served",
        mechanism_config={"typical_booking_lead_time_months": 12},
        issuing_authority="government", competitiveness_level="very_high",
        source_url="https://www.sanparks.org/parks/garden_route/tourism/activity/otter_trail",
        name_he="שביל האוטר",
        description_en="South Africa's oldest and most famous coastal hiking trail, limited to 12 hikers per day through Tsitsikamma section of Garden Route National Park.",
        mechanism_explanation_en="Only 12 hikers may start per day and SANParks opens bookings exactly 13 months ahead - popular dates are typically fully booked within hours of opening.",
        checklist=[
            ("document", "SANParks booking confirmation with assigned start date", True),
            ("payment", "Full trail fee paid at booking", True),
            ("gear", "Dry bag for the mandatory Bloukrans River crossing", True),
        ],
    ),
    dict(
        country="Costa Rica", category="trek", name="Chirripó National Park",
        mechanism_type="first_come_first_served",
        mechanism_config={"typical_booking_lead_time_months": 2},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.sinac.go.cr/",
        name_he="פארק צ'יריפו",
        description_en="A 2-day trek to Cerro Chirripó, Costa Rica's highest peak, with an overnight stay at the base lodge.",
        mechanism_explanation_en="SINAC caps daily hikers and requires a base-lodge (albergue) bed reservation; bookings open on a rolling basis about 2 months ahead and fill quickly in dry season.",
        checklist=[
            ("document", "Trail permit + albergue bed reservation", True),
            ("gear", "Warm layers - summit temperatures can drop below freezing", True),
            ("payment", "Lodge and park fees, generally prepaid", True),
        ],
    ),
    dict(
        country="Vietnam", category="tourist_attraction", name="Son Doong Cave",
        mechanism_type="single_operator_annual_quota",
        mechanism_config={"operator_name": "Oxalis Adventure", "annual_quota": 1000, "typical_booking_lead_time_months": 12},
        issuing_authority="mixed", competitiveness_level="high",
        source_url="https://oxalis.com.vn/",
        name_he="מערת סון דונג",
        description_en="The largest cave passage in the world, reached via a 4-day jungle expedition in Phong Nha-Ke Bang National Park.",
        mechanism_explanation_en="Oxalis Adventure holds the sole government concession to lead Son Doong expeditions, capped at roughly 1,000 visitors per year across the short annual dry-season window (Jan-Aug); trips book out about a year ahead.",
        checklist=[
            ("action", "Book directly with Oxalis Adventure - no other operator is licensed", True),
            ("document", "Expedition permit (arranged by Oxalis as part of the trip)", True),
            ("payment", "Full expedition payment, generally required well in advance", True),
            ("gear", "Trekking-graded fitness - the route includes technical caving sections", False),
        ],
    ),
    dict(
        country="USA", category="tourist_attraction", name="Antelope Canyon",
        mechanism_type="guided_tour_only",
        mechanism_config={},
        issuing_authority="tribal", competitiveness_level="medium",
        source_url="https://navajonationparks.org/tribal-parks/antelope-canyon/",
        name_he="קניון אנטילופה",
        description_en="A famous slot canyon on Navajo Nation land near Page, Arizona, known for its light beams and flowing sandstone walls.",
        mechanism_explanation_en="Entry is only possible with a licensed Navajo guide/tour operator - there is no independent access and no fixed release date, just tour availability.",
        checklist=[
            ("action", "Book a tour with a licensed Navajo operator", True),
            ("document", "Navajo Nation tribal park permit (included in tour price)", True),
            ("gear", "Camera strap - hands-free is required on some tours", False),
        ],
    ),
    dict(
        country="Ireland", category="tourist_attraction", name="Skellig Michael",
        mechanism_type="guided_tour_only",
        mechanism_config={},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.heritageireland.ie/visit-a-site/skellig-michael/",
        name_he="סקליג מייקל",
        description_en="A remote island monastery off Ireland's southwest coast, reached by licensed boat operators - weather-dependent and often cancelled.",
        mechanism_explanation_en="Only 15 licensed boats may land daily and each carries a strict passenger cap; there is no fixed release date, only boat-operator availability and frequent weather cancellations.",
        checklist=[
            ("action", "Book with one of the licensed Skellig Michael boat operators", True),
            ("document", "OPW island landing permit (included via your boat operator)", True),
            ("gear", "Sturdy shoes - 600+ uneven stone steps to the monastery", True),
        ],
    ),
    dict(
        country="Dominican Republic", category="seasonal_nature_event", name="Silver Bank Whale Swimming",
        mechanism_type="guided_tour_only",
        mechanism_config={},
        issuing_authority="commercial", competitiveness_level="medium",
        source_url="https://consciousbreathadventures.com/",
        name_he="שחייה עם לווייתנים - סילבר בנק",
        description_en="In-water encounters with humpback whales on their winter breeding grounds at the Silver Bank marine sanctuary.",
        mechanism_explanation_en="Access is only via a handful of licensed liveaboard operators during the short Jan-Apr whale season; there's no fixed release date, just operator boat-trip availability that books out well ahead.",
        checklist=[
            ("action", "Book a berth on a licensed liveaboard during whale season (Jan-Apr)", True),
            ("document", "Sanctuary permit (arranged by your operator)", True),
            ("gear", "Own snorkel gear (mask/fins), some boats provide it - confirm with operator", False),
        ],
    ),
    dict(
        country="India", category="wildlife_safari", name="Tiger Reserve Safaris — Ranthambore/Corbett/Bandhavgarh",
        mechanism_type="fixed_daily_quota",
        mechanism_config={"daily_quota": 60, "booking_opens_days_before": 90},
        issuing_authority="government", competitiveness_level="high",
        source_url="https://www.rajasthanwildlifebooking.com/",
        name_he="ספארי בשמורות הנמרים - הודו",
        description_en="Jeep safaris in India's flagship tiger reserves, booked per zone and per morning/afternoon shift.",
        mechanism_explanation_en="Each reserve caps the number of jeeps per zone per shift and opens online booking on a rolling basis roughly 90 days ahead; popular zones and weekend shifts sell out within a day.",
        checklist=[
            ("document", "Zone-specific safari booking confirmation", True),
            ("document", "Photo ID matching the booking (checked at the gate)", True),
            ("action", "Arrive 30+ minutes before your shift's gate time", True),
        ],
    ),
]
