"""add checklist_completions and lead_time_minutes

Revision ID: 61f5d9a4b379
Revises: acd0d2f20bde
Create Date: 2026-08-31 14:51:13.550313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '61f5d9a4b379'
down_revision: Union[str, None] = 'acd0d2f20bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_completions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('prep_item_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'prep_item_id', name='uq_completion_user_item')
    )
    op.create_index(op.f('ix_checklist_completions_destination_id'), 'checklist_completions', ['destination_id'], unique=False)
    op.create_index(op.f('ix_checklist_completions_user_id'), 'checklist_completions', ['user_id'], unique=False)
    op.add_column('alert_subscriptions', sa.Column('lead_time_minutes', sa.Integer(), nullable=False))
    op.drop_column('alert_subscriptions', 'lead_time_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_subscriptions', sa.Column('lead_time_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('alert_subscriptions', 'lead_time_minutes')
    op.drop_index(op.f('ix_checklist_completions_user_id'), table_name='checklist_completions')
    op.drop_index(op.f('ix_checklist_completions_destination_id'), table_name='checklist_completions')
    op.drop_table('checklist_completions')
    # ### end Alembic commands ###
