"""initial schema

Revision ID: 6573f12a9b23
Revises: 
Create Date: 2026-08-31 10:00:39.407756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6573f12a9b23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('destinations',
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('trek', 'national_park_entry', 'camping', 'diving', 'wildlife_safari', 'thru_hike', 'tourist_attraction', 'seasonal_nature_event', name='category'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mechanism_type', sa.Enum('fixed_daily_quota', 'lottery', 'rolling_window', 'fixed_annual_date', 'weekly_release', 'guided_tour_only', 'single_operator_annual_quota', 'first_come_first_served', name='mechanism_type'), nullable=False),
    sa.Column('mechanism_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issuing_authority', sa.Enum('government', 'tribal', 'commercial', 'mixed', name='issuing_authority'), nullable=False),
    sa.Column('competitiveness_level', sa.Enum('low', 'medium', 'high', 'very_high', name='competitiveness_level'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('general_requirements',
    sa.Column('requirement_type', sa.Enum('passport_validity', 'visa', 'vaccination', 'travel_insurance', 'fitness_certificate', 'other', name='requirement_type'), nullable=False),
    sa.Column('title_key', sa.String(), nullable=False),
    sa.Column('description_key', sa.String(), nullable=False),
    sa.Column('is_general_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'locale', name='uq_translation_entity_locale')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('preferred_locale', sa.String(length=8), nullable=False),
    sa.Column('theme_preference', sa.Enum('light', 'dark', 'system', name='theme_preference'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alert_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_subscriptions_destination_id'), 'alert_subscriptions', ['destination_id'], unique=False)
    op.create_index(op.f('ix_alert_subscriptions_user_id'), 'alert_subscriptions', ['user_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('document', 'action', 'gear', 'payment', name='checklist_item_type'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('text_key', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destination_requirements',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('general_requirement_id', sa.UUID(), nullable=False),
    sa.Column('destination_specific_note_key', sa.String(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['general_requirement_id'], ['general_requirements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destination_requirements_destination_id'), 'destination_requirements', ['destination_id'], unique=False)
    op.create_index(op.f('ix_destination_requirements_general_requirement_id'), 'destination_requirements', ['general_requirement_id'], unique=False)
    op.create_table('monitoring_snapshots',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_text_excerpt', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_snapshots_destination_id'), 'monitoring_snapshots', ['destination_id'], unique=False)
    op.create_table('purchases',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('web', 'ios', 'android', name='platform'), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'completed', 'refunded', 'failed', name='purchase_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_intent_id')
    )
    op.create_index(op.f('ix_purchases_destination_id'), 'purchases', ['destination_id'], unique=False)
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('monitoring_diffs',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('previous_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('new_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=False),
    sa.Column('review_status', sa.Enum('pending', 'approved', 'dismissed', name='review_status'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['new_snapshot_id'], ['monitoring_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_snapshot_id'], ['monitoring_snapshots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_diffs_destination_id'), 'monitoring_diffs', ['destination_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('sent', 'failed', name='notification_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['alert_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_subscription_id'), 'notification_log', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_log_subscription_id'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_monitoring_diffs_destination_id'), table_name='monitoring_diffs')
    op.drop_table('monitoring_diffs')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_destination_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_monitoring_snapshots_destination_id'), table_name='monitoring_snapshots')
    op.drop_table('monitoring_snapshots')
    op.drop_index(op.f('ix_destination_requirements_general_requirement_id'), table_name='destination_requirements')
    op.drop_index(op.f('ix_destination_requirements_destination_id'), table_name='destination_requirements')
    op.drop_table('destination_requirements')
    op.drop_table('checklist_items')
    op.drop_index(op.f('ix_alert_subscriptions_user_id'), table_name='alert_subscriptions')
    op.drop_index(op.f('ix_alert_subscriptions_destination_id'), table_name='alert_subscriptions')
    op.drop_table('alert_subscriptions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('translations')
    op.drop_table('general_requirements')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
