"""add contact message reply fields

Revision ID: acd0d2f20bde
Revises: e4a3753c698d
Create Date: 2026-08-31 14:45:30.592761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acd0d2f20bde'
down_revision: Union[str, None] = 'e4a3753c698d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('admin_reply', sa.Text(), nullable=True))
    op.add_column('contact_messages', sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_messages', 'replied_at')
    op.drop_column('contact_messages', 'admin_reply')
    # ### end Alembic commands ###
