"""add application_url to destinations

Revision ID: e4a3753c698d
Revises: 5acae2ca9a5e
Create Date: 2026-08-31 12:54:26.469972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4a3753c698d'
down_revision: Union[str, None] = '5acae2ca9a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('application_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('destinations', 'application_url')
    # ### end Alembic commands ###
