"""
Draft machine-translated content for non-English locales (spec addendum §3).
Generated by Claude as a first pass, not human-verified - see README.md's
"Decisions made where the spec was ambiguous" section for the caveat that applies
to every string in this file. English (seed_data.py / seed_data_requirements.py)
remains the source of truth; any locale missing here falls back to English
automatically via app/services/i18n.py.

Loaded by app/jobs/seed_i18n.py.
"""

DESTINATION_TRANSLATIONS = {
    "Inca Trail": {
        "he": {
            "name": "שביל האינקה",
            "description": "הטרק הקלאסי בן 4 הימים למאצ'ו פיצ'ו דרך האנדים הפרואניים, המסתיים בשער השמש.",
            "mechanism_explanation": "מכסה יומית קשיחה של 500 היתרים (מטיילים בתוספת מדריכים וסבלים) נמכרת דרך סוכנויות טיולים מורשות, בדרך כלל 5-6 חודשים לפני עונת השיא.",
            "checklist": [
                "דרכון בתוקף (חייב להתאים בדיוק לשם על ההיתר)",
                "הזמנה דרך סוכנות טיולים מורשית - טרק עצמאי אינו מותר",
                "אישור הזמנה / מספר היתר מהסוכנות",
                "שק שינה המתאים ללילות קרים (המחנות נמצאים מעל 3,000 מ')",
                "תשלום מלא עבור הטרק, נדרש בדרך כלל מראש להבטחת ההיתר",
            ],
        },
        "de": {
            "name": "Inka-Trail",
            "description": "Der klassische 4-tägige Trek nach Machu Picchu durch die peruanischen Anden, der am Sonnentor endet.",
            "mechanism_explanation": "Eine feste Tagesobergrenze von 500 Genehmigungen (Wanderer plus Guides und Träger) wird über lizenzierte Reiseveranstalter verkauft, in der Regel 5-6 Monate vor der Hauptsaison.",
            "checklist": [
                "Gültiger Reisepass (muss exakt mit dem Namen auf Ihrer Genehmigung übereinstimmen)",
                "Buchung über einen lizenzierten Reiseveranstalter - unabhängiges Trekking ist nicht erlaubt",
                "Buchungsbestätigung / Genehmigungsnummer Ihres Veranstalters",
                "Schlafsack für kalte Nächte geeignet (Lager liegen über 3.000 m)",
                "Vollständige Zahlung für den Trek, in der Regel im Voraus zur Sicherung der Genehmigung erforderlich",
            ],
        },
        "fr": {
            "name": "Chemin de l'Inca",
            "description": "Le trek classique de 4 jours vers le Machu Picchu à travers les Andes péruviennes, se terminant à la Porte du Soleil.",
            "mechanism_explanation": "Un quota quotidien strict de 500 permis (randonneurs plus guides et porteurs) est vendu par des agences de voyage agréées, généralement 5 à 6 mois avant la haute saison.",
            "checklist": [
                "Passeport valide (doit correspondre exactement au nom figurant sur votre permis)",
                "Réservation via une agence agréée - la randonnée indépendante n'est pas autorisée",
                "Confirmation de réservation / numéro de permis de votre agence",
                "Sac de couchage adapté aux nuits froides (les campements sont à plus de 3 000 m)",
                "Paiement complet du trek, généralement requis à l'avance pour garantir le permis",
            ],
        },
        "es": {
            "name": "Camino Inca",
            "description": "El clásico trekking de 4 días a Machu Picchu a través de los Andes peruanos, que termina en la Puerta del Sol.",
            "mechanism_explanation": "Se vende un cupo diario fijo de 500 permisos (excursionistas más guías y porteadores) a través de operadores turísticos autorizados, normalmente con 5-6 meses de antelación a la temporada alta.",
            "checklist": [
                "Pasaporte válido (debe coincidir exactamente con el nombre de tu permiso)",
                "Reserva a través de un operador turístico autorizado - no se permite el trekking independiente",
                "Confirmación de reserva / número de permiso de tu operador",
                "Saco de dormir apto para noches frías (los campamentos están por encima de los 3.000 m)",
                "Pago completo del trekking, normalmente requerido por adelantado para asegurar el permiso",
            ],
        },
        "pt-BR": {
            "name": "Trilha Inca",
            "description": "A clássica trilha de 4 dias até Machu Picchu pelos Andes peruanos, terminando na Porta do Sol.",
            "mechanism_explanation": "Uma cota diária fixa de 500 permissões (caminhantes, além de guias e carregadores) é vendida por operadoras licenciadas, geralmente com 5 a 6 meses de antecedência em relação à alta temporada.",
            "checklist": [
                "Passaporte válido (deve corresponder exatamente ao nome na sua permissão)",
                "Reserva feita por meio de uma operadora licenciada - trekking independente não é permitido",
                "Confirmação de reserva / número da permissão da sua operadora",
                "Saco de dormir adequado para noites frias (os acampamentos ficam acima de 3.000 m)",
                "Pagamento integral da trilha, geralmente exigido com antecedência para garantir a permissão",
            ],
        },
    },
    "Mountain Gorilla Trekking – Volcanoes NP": {
        "he": {
            "name": "מסע לצפייה בגורילות הרים",
            "description": "טרק מודרך לביקור באחת ממשפחות הגורילות המורגלות בפארק הלאומי הרי הגעש.",
            "mechanism_explanation": "מותרים 8 מבקרים למשפחת גורילות ביום בלבד, מתוך כ-12 משפחות מורגלות. ניתן להזמין היתרים עד שנה מראש, והם אוזלים מוקדם בעונת השיא (יוני-ספטמבר, דצמבר-פברואר).",
            "checklist": [
                "היתר גורילות (מונפק על ידי רשות הפיתוח של רואנדה)",
                "דרכון בתוקף ל-6 חודשים לפחות",
                "נעלי הליכה יציבות ועמידות במים",
                "כפפות גינון לאחיזה בצמחייה בשביל",
                "הגעה למטה הפארק לתדריך בשעה 07:00 ביום הטרק",
            ],
        },
        "de": {
            "name": "Berggorilla-Trekking – Volcanoes-Nationalpark",
            "description": "Ein geführter Trek zu einer der habituierten Gorillafamilien im Volcanoes-Nationalpark.",
            "mechanism_explanation": "Nur 8 Besucher pro Gorillafamilie und Tag sind erlaubt, bei etwa 12 habituierten Familien. Genehmigungen können bis zu einem Jahr im Voraus gebucht werden und sind in der Hauptsaison (Juni-Sept, Dez-Feb) früh ausgebucht.",
            "checklist": [
                "Gorilla-Genehmigung (ausgestellt vom Rwanda Development Board)",
                "Reisepass mit mindestens 6 Monaten Gültigkeit",
                "Robuste, wasserdichte Wanderschuhe",
                "Gartenhandschuhe zum Festhalten an Vegetation auf dem Pfad",
                "Ankunft am Park-Hauptquartier für die Einweisung um 07:00 Uhr am Trekkingtag",
            ],
        },
        "fr": {
            "name": "Trek des gorilles de montagne – Parc national des Volcans",
            "description": "Un trek guidé pour rencontrer l'une des familles de gorilles habituées dans le Parc national des Volcans.",
            "mechanism_explanation": "Seuls 8 visiteurs par famille de gorilles et par jour sont autorisés, sur environ 12 familles habituées. Les permis peuvent être réservés jusqu'à un an à l'avance et s'épuisent tôt en haute saison (juin-sept, déc-fév).",
            "checklist": [
                "Permis gorille (délivré par le Rwanda Development Board)",
                "Passeport valide au moins 6 mois",
                "Chaussures de randonnée robustes et imperméables",
                "Gants de jardinage pour s'accrocher à la végétation sur le sentier",
                "Arrivée au QG du parc pour le briefing de 7h00 le jour du trek",
            ],
        },
        "es": {
            "name": "Trekking de gorilas de montaña – Parque Nacional de los Volcanes",
            "description": "Un trekking guiado para visitar una de las familias de gorilas habituadas en el Parque Nacional de los Volcanes.",
            "mechanism_explanation": "Solo se permiten 8 visitantes por familia de gorilas al día, entre unas 12 familias habituadas. Los permisos se pueden reservar hasta con un año de antelación y se agotan pronto en temporada alta (junio-sept, dic-feb).",
            "checklist": [
                "Permiso de gorilas (emitido por el Rwanda Development Board)",
                "Pasaporte válido por 6 meses o más",
                "Botas de senderismo resistentes e impermeables",
                "Guantes tipo jardinería para sujetarse a la vegetación del sendero",
                "Llegada a la sede del parque para la charla informativa de las 07:00 el día del trekking",
            ],
        },
        "pt-BR": {
            "name": "Trekking de gorilas-da-montanha – Parque Nacional dos Vulcões",
            "description": "Uma trilha guiada para visitar uma das famílias de gorilas habituadas no Parque Nacional dos Vulcões.",
            "mechanism_explanation": "Apenas 8 visitantes por família de gorilas por dia são permitidos, entre cerca de 12 famílias habituadas. As permissões podem ser reservadas com até um ano de antecedência e se esgotam cedo na alta temporada (junho-set, dez-fev).",
            "checklist": [
                "Permissão para gorilas (emitida pelo Rwanda Development Board)",
                "Passaporte válido por 6 meses ou mais",
                "Botas de caminhada resistentes e impermeáveis",
                "Luvas de jardinagem para se apoiar na vegetação da trilha",
                "Chegada à sede do parque para o briefing das 07h00 no dia da trilha",
            ],
        },
    },
    "Sipadan": {
        "he": {
            "name": "סיפדן",
            "description": "אחד מאתרי הצלילה המובילים בעולם, ידוע בטורנדו הברקודות ובצבי הים - הכניסה מוגבלת כדי להגן על השונית.",
            "mechanism_explanation": "רשות פארקי סבאח מגבילה את סיפדן ל-176 היתרי צלילה ביום בדיוק, המוקצים למפעילי צלילה במאבול/סמפורנה הסמוכות. ההיתרים מסודרים בדרך כלל על ידי אתר הצלילה 2-3 חודשים מראש.",
            "checklist": [
                "היתר צלילה לסיפדן (מסודר על ידי האתר/המפעיל שלכם)",
                "הוכחת הסמכת Open Water (או גבוהה יותר)",
                "מחשב צלילה אישי (מומלץ, לא תמיד מסופק)",
                "אגרת שימור לפארק הימי",
            ],
        },
        "de": {
            "name": "Sipadan",
            "description": "Einer der weltweit besten Tauchplätze, berühmt für Barrakuda-Tornados und Grüne Meeresschildkröten - der Zugang ist begrenzt, um das Riff zu schützen.",
            "mechanism_explanation": "Sabah Parks begrenzt Sipadan auf genau 176 Taucherlaubnisse pro Tag, die an Tauchanbieter im nahen Mabul/Semporna vergeben werden. Genehmigungen werden in der Regel von Ihrem Tauchresort 2-3 Monate im Voraus organisiert.",
            "checklist": [
                "Sipadan-Tauchgenehmigung (von Ihrem Resort/Anbieter organisiert)",
                "Nachweis der Open-Water-Zertifizierung (oder höher)",
                "Eigener Tauchcomputer (empfohlen, nicht immer gestellt)",
                "Gebühr für den Meeresschutzpark",
            ],
        },
        "fr": {
            "name": "Sipadan",
            "description": "L'un des meilleurs sites de plongée au monde, célèbre pour ses tornades de barracudas et ses tortues vertes - l'accès est limité pour protéger le récif.",
            "mechanism_explanation": "Sabah Parks limite Sipadan à exactement 176 permis de plongée par jour, attribués aux opérateurs de plongée basés à proximité de Mabul/Semporna. Les permis sont généralement organisés par votre centre de plongée 2 à 3 mois à l'avance.",
            "checklist": [
                "Permis de plongée pour Sipadan (organisé par votre centre/opérateur)",
                "Preuve de certification Open Water (ou supérieure)",
                "Votre propre ordinateur de plongée (recommandé, pas toujours fourni)",
                "Frais de conservation du parc marin",
            ],
        },
        "es": {
            "name": "Sipadan",
            "description": "Uno de los mejores lugares de buceo del mundo, famoso por sus tornados de barracudas y tortugas verdes - el acceso está limitado para proteger el arrecife.",
            "mechanism_explanation": "Sabah Parks limita Sipadan a exactamente 176 permisos de buceo por día, asignados a operadores de buceo con base en la cercana Mabul/Semporna. Los permisos suelen gestionarse a través de tu centro de buceo con 2-3 meses de antelación.",
            "checklist": [
                "Permiso de buceo para Sipadan (gestionado por tu centro/operador)",
                "Certificación Open Water (o superior)",
                "Tu propio ordenador de buceo (recomendado, no siempre se proporciona)",
                "Tasa de conservación del parque marino",
            ],
        },
        "pt-BR": {
            "name": "Sipadan",
            "description": "Um dos melhores pontos de mergulho do mundo, famoso pelos redemoinhos de barracudas e tartarugas-verdes - o acesso é limitado para proteger o recife.",
            "mechanism_explanation": "O Sabah Parks limita Sipadan a exatamente 176 permissões de mergulho por dia, distribuídas entre operadoras de mergulho baseadas em Mabul/Semporna, nas proximidades. As permissões geralmente são providenciadas pelo seu resort de mergulho com 2 a 3 meses de antecedência.",
            "checklist": [
                "Permissão de mergulho para Sipadan (providenciada pelo seu resort/operadora)",
                "Comprovante de certificação Open Water (ou superior)",
                "Computador de mergulho próprio (recomendado, nem sempre fornecido)",
                "Taxa de conservação do parque marinho",
            ],
        },
    },
    "Corcovado NP – Sirena Station": {
        "he": {
            "name": "פארק קורקובדו - תחנת סירנה",
            "description": "תחנת הרינג'רים המרוחקת והעשירה ביותר בחיות בר בפארק הלאומי קורקובדו, הנגישה רק בסירה, במטוס, או בטרק של יום שלם.",
            "mechanism_explanation": "SINAC מגבילה את מספר המבקרים היומי בתחנת סירנה ומחייבת מדריך מקומי מוסמך לכניסה; יש להזמין דרך SINAC או מפעיל מורשה כחודש מראש בעונת השיא.",
            "checklist": [
                "הזמנה דרך SINAC או מפעיל מורשה עם מדריך מוסמך",
                "היתר כניסה לפארק / אישור הזמנה",
                "מגפי גומי או נעליים מתייבשות מהר למעברי נהר",
                "דמי כניסה לפארק",
            ],
        },
        "de": {
            "name": "Corcovado-Nationalpark – Sirena-Station",
            "description": "Die abgelegenste und wildtierreichste Ranger-Station im Corcovado-Nationalpark, nur per Boot, Flugzeug oder ganztägiger Wanderung erreichbar.",
            "mechanism_explanation": "SINAC begrenzt die tägliche Besucherzahl an der Sirena-Station und verlangt einen zertifizierten örtlichen Guide für den Zutritt; Buchung über SINAC oder einen autorisierten Anbieter etwa einen Monat im Voraus in der Hauptsaison.",
            "checklist": [
                "Buchung über SINAC oder einen lizenzierten Anbieter mit zertifiziertem Guide",
                "Parkeintrittsgenehmigung / Reservierungsbestätigung",
                "Gummistiefel oder schnelltrocknende Schuhe für Flussüberquerungen",
                "Parkeintrittsgebühr",
            ],
        },
        "fr": {
            "name": "Parc national de Corcovado – Station de Sirena",
            "description": "La station de rangers la plus reculée et la plus riche en faune du parc national de Corcovado, accessible uniquement en bateau, en avion ou par une randonnée d'une journée complète.",
            "mechanism_explanation": "Le SINAC limite le nombre de visiteurs quotidiens à la station de Sirena et exige un guide local certifié pour l'entrée ; réservation via le SINAC ou un opérateur agréé environ un mois à l'avance en haute saison.",
            "checklist": [
                "Réservation via le SINAC ou un opérateur agréé avec guide certifié",
                "Permis d'entrée au parc / confirmation de réservation",
                "Bottes en caoutchouc ou chaussures à séchage rapide pour les traversées de rivière",
                "Frais d'entrée au parc",
            ],
        },
        "es": {
            "name": "Parque Nacional Corcovado – Estación Sirena",
            "description": "La estación de guardaparques más remota y rica en fauna del Parque Nacional Corcovado, accesible solo en barco, avión o una caminata de un día completo.",
            "mechanism_explanation": "El SINAC limita el número diario de visitantes en la Estación Sirena y exige un guía local certificado para el ingreso; reserva a través del SINAC o un operador autorizado con un mes de antelación en temporada alta.",
            "checklist": [
                "Reserva a través del SINAC o un operador autorizado con guía certificado",
                "Permiso de entrada al parque / confirmación de reserva",
                "Botas de goma o calzado de secado rápido para cruces de ríos",
                "Tarifa de entrada al parque",
            ],
        },
        "pt-BR": {
            "name": "Parque Nacional Corcovado – Estação Sirena",
            "description": "A estação de guarda-parques mais remota e rica em vida selvagem do Parque Nacional Corcovado, acessível apenas de barco, avião ou uma trilha de dia inteiro.",
            "mechanism_explanation": "O SINAC limita o número diário de visitantes na Estação Sirena e exige um guia local certificado para a entrada; reserve pelo SINAC ou uma operadora licenciada cerca de um mês antes na alta temporada.",
            "checklist": [
                "Reserva pelo SINAC ou por uma operadora licenciada com guia certificado",
                "Permissão de entrada no parque / confirmação de reserva",
                "Botas de borracha ou calçado de secagem rápida para travessias de rios",
                "Taxa de entrada no parque",
            ],
        },
    },
    "Half Dome": {
        "he": {
            "name": "הכיפה החצויה",
            "description": "העלייה האייקונית המסייעת בכבלים לפסגת הכיפה החצויה בפארק הלאומי יוסמיטי.",
            "mechanism_explanation": "הגרלה מוקדמת מתקיימת בכל מרץ עבור כל עונת הטיולים; הגרלה יומית קטנה יותר נפתחת גם יומיים לפני כל תאריך טיול עבור היתרים שנותרו.",
            "checklist": [
                "השתתפות בהגרלה המוקדמת באתר recreation.gov במרץ",
                "היתר כיפה חצויה (אחד לכל מטייל, יש לשאת אותו)",
                "כפפות לקטע הכבלים",
                "כרטיס כניסה לפארק יוסמיטי",
            ],
        },
        "de": {
            "name": "Half Dome",
            "description": "Der ikonische, mit Seilen gesicherte Schlussanstieg zum Gipfel des Half Dome im Yosemite-Nationalpark.",
            "mechanism_explanation": "Jeden März findet eine Vorsaison-Verlosung für die gesamte Wandersaison statt; eine kleinere Tagesverlosung öffnet zudem 2 Tage vor jedem Wandertermin für übrig gebliebene Genehmigungen.",
            "checklist": [
                "Teilnahme an der Vorsaison-Verlosung auf recreation.gov im März",
                "Half-Dome-Genehmigung (eine pro Wanderer, muss mitgeführt werden)",
                "Handschuhe für den Kabelabschnitt",
                "Eintrittskarte für den Yosemite-Nationalpark",
            ],
        },
        "fr": {
            "name": "Half Dome",
            "description": "La montée finale emblématique assistée par câbles jusqu'au sommet du Half Dome dans le parc national de Yosemite.",
            "mechanism_explanation": "Un tirage au sort de présaison a lieu chaque mois de mars pour toute la saison de randonnée ; un tirage quotidien plus restreint s'ouvre également 2 jours avant chaque date de randonnée pour les permis restants.",
            "checklist": [
                "Participer au tirage au sort de présaison sur recreation.gov en mars",
                "Permis Half Dome (un par randonneur, à porter sur soi)",
                "Gants pour la section des câbles",
                "Billet d'entrée au parc de Yosemite",
            ],
        },
        "es": {
            "name": "Half Dome",
            "description": "El icónico ascenso final asistido por cables hasta la cima de Half Dome en el Parque Nacional de Yosemite.",
            "mechanism_explanation": "Cada marzo se celebra un sorteo de pretemporada para toda la temporada de senderismo; también se abre un sorteo diario más pequeño 2 días antes de cada fecha de excursión para los permisos restantes.",
            "checklist": [
                "Participar en el sorteo de pretemporada en recreation.gov en marzo",
                "Permiso de Half Dome (uno por excursionista, debe llevarse encima)",
                "Guantes para la sección de cables",
                "Entrada al Parque de Yosemite",
            ],
        },
        "pt-BR": {
            "name": "Half Dome",
            "description": "A icônica subida final com auxílio de cabos até o topo do Half Dome, no Parque Nacional de Yosemite.",
            "mechanism_explanation": "Um sorteio de pré-temporada acontece todo mês de março para toda a temporada de trilhas; um sorteio diário menor também abre 2 dias antes de cada data de trilha para permissões remanescentes.",
            "checklist": [
                "Participar do sorteio de pré-temporada no recreation.gov em março",
                "Permissão do Half Dome (uma por caminhante, deve ser carregada)",
                "Luvas para o trecho dos cabos",
                "Ingresso de entrada do Parque de Yosemite",
            ],
        },
    },
    # DESTINATIONS_MARKER
}

GENERAL_REQUIREMENT_TRANSLATIONS = {
    # REQUIREMENTS_MARKER
}

DESTINATION_REQUIREMENT_NOTE_TRANSLATIONS = {
    # NOTES_MARKER
}
